name: cla-check

on:
  pull_request:
    branches:
      - main
      - 'release-[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  cla-check:
    permissions:
      pull-requests: write  # for canonical/has-signed-canonical-cla to create & update comments
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@69c2bf9c2d882e51d482333cbb3c0978826855b6 # v1
