name: SBOM

on:
  push:
    branches:
      - main
      - autoupdate/strict
      - 'release-[0-9]+.[0-9]+'
      - 'release-[0-9]+.[0-9]+-strict'
  pull_request:
    branches:
      - main
      - 'release-[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip3 install -r ./build-scripts/hack/requirements.txt
      - name: Build SBOM
        run: |
          ./build-scripts/hack/generate-sbom.py sbom.tar.gz
          tar xvzf sbom.tar.gz
      - name: Upload SBOM
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: sbom
          path: sbom
