name: Check for component upgrades

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          # Keep main branch up to date
          - main
          # Supported stable release branches
          - release-1.30

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checking out repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ matrix.branch }}
          ssh-key: ${{ secrets.DEPLOY_KEY_TO_UPDATE_STRICT_BRANCH }}

      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip3 install -r ./build-scripts/hack/requirements.txt

      - name: Check for new component versions
        run: |
          ./build-scripts/hack/update-component-versions.py

      - name: Create pull request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with:
          git-token: ${{ secrets.DEPLOY_KEY_TO_UPDATE_STRICT_BRANCH }}
          commit-message: "[${{ matrix.branch }}] Update component versions"
          title: "[${{ matrix.branch }}] Update component versions"
          body: "[${{ matrix.branch }}] Update component versions"
          branch: "autoupdate/sync/${{ matrix.branch }}"
          delete-branch: true
          base: ${{ matrix.branch }}
